set_property -dict {PACKAGE_PIN J18  IOSTANDARD TMDS_33 } [get_ports {tmds_data_p[2]}]
set_property -dict {PACKAGE_PIN K19  IOSTANDARD TMDS_33 } [get_ports {tmds_data_p[1]}]
set_property -dict {PACKAGE_PIN K17  IOSTANDARD TMDS_33 } [get_ports {tmds_data_p[0]}]
set_property -dict {PACKAGE_PIN L16  IOSTANDARD TMDS_33 } [get_ports tmds_clk_p]

set_property -dict {PACKAGE_PIN R14  IOSTANDARD LVCMOS33} [get_ports led]
set_property -dict {PACKAGE_PIN D19  IOSTANDARD LVCMOS33} [get_ports key0]
set_property -dict {PACKAGE_PIN D20  IOSTANDARD LVCMOS33} [get_ports key1]
set_property -dict {PACKAGE_PIN L19  IOSTANDARD LVCMOS33} [get_ports key3]
#----------------------摄像头接口---------------------------
set_property PULLUP true [get_ports cmos_sclk]
set_property PULLUP true [get_ports cmos_sdat]
create_clock -period 41.600 -name cmos_pclk -waveform {0.000 20.800} [get_ports cmos_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos_pclk_IBUF]

set_property -dict {PACKAGE_PIN W13  IOSTANDARD LVCMOS33} [get_ports cmos_sclk]
set_property -dict {PACKAGE_PIN T10  IOSTANDARD LVCMOS33} [get_ports cmos_sdat]
set_property -dict {PACKAGE_PIN W16  IOSTANDARD LVCMOS33} [get_ports cmos_pclk]
set_property -dict {PACKAGE_PIN Y14  IOSTANDARD LVCMOS33} [get_ports cmos_xclk]
set_property -dict {PACKAGE_PIN V12  IOSTANDARD LVCMOS33} [get_ports cmos_vsync]
set_property -dict {PACKAGE_PIN T11  IOSTANDARD LVCMOS33} [get_ports cmos_href]
set_property -dict {PACKAGE_PIN U18  IOSTANDARD LVCMOS33} [get_ports cmos_rst_n]
set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS33} [get_ports cmos_pwdn]

set_property -dict {PACKAGE_PIN V16  IOSTANDARD LVCMOS33} [get_ports {cmos_data[7]}]
set_property -dict {PACKAGE_PIN W14  IOSTANDARD LVCMOS33} [get_ports {cmos_data[6]}]
set_property -dict {PACKAGE_PIN W19  IOSTANDARD LVCMOS33} [get_ports {cmos_data[5]}]
set_property -dict {PACKAGE_PIN Y17  IOSTANDARD LVCMOS33} [get_ports {cmos_data[4]}]
set_property -dict {PACKAGE_PIN W18  IOSTANDARD LVCMOS33} [get_ports {cmos_data[3]}]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS33} [get_ports {cmos_data[2]}]
set_property -dict {PACKAGE_PIN U19  IOSTANDARD LVCMOS33} [get_ports {cmos_data[1]}]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS33} [get_ports {cmos_data[0]}]

set_false_path -from [get_clocks cmos_pclk] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_out1_sys_clk_ctrl] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_out3_sys_clk_ctrl] -to [get_clocks cmos_pclk]